apiVersion: v1
kind: Secret
metadata:
  name: external-dns-unifi-webhook-env
  namespace: external-dns
type: Opaque
stringData:
  UNIFI_HOST: http://192.168.2.1
  UNIFI_API_KEY: uZUEeKS8L2GjmYEcgUjh0w6qh_MOXutp
  UNIFI_SITE: default
  UNIFI_SKIP_TLS_VERIFY: "true"
