apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: cert-manager-cloudflare-token
  namespace: doppler-operator-system
spec:
  # Create a Doppler Service Account Identity and paste its ID here.
  # Audience format:
  # dopplerSecret:doppler-operator-system:cert-manager-cloudflare-token
  identity: "REPLACE_WITH_DOPPLER_IDENTITY_ID"
  project: "REPLACE_WITH_DOPPLER_PROJECT"
  config: "REPLACE_WITH_DOPPLER_CONFIG"
  managedSecret:
    name: cloudflare-api-token
    namespace: cert-manager
    type: Opaque
  secrets:
    - CLOUDFLARE_API_TOKEN
  processors:
    CLOUDFLARE_API_TOKEN:
      type: plain
      asName: api-token
---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: external-dns-cloudflare-token
  namespace: doppler-operator-system
spec:
  # Audience format:
  # dopplerSecret:doppler-operator-system:external-dns-cloudflare-token
  identity: "REPLACE_WITH_DOPPLER_IDENTITY_ID"
  project: "REPLACE_WITH_DOPPLER_PROJECT"
  config: "REPLACE_WITH_DOPPLER_CONFIG"
  managedSecret:
    name: external-dns-cloudflare
    namespace: external-dns
    type: Opaque
  secrets:
    - CLOUDFLARE_API_TOKEN
  processors:
    CLOUDFLARE_API_TOKEN:
      type: plain
      asName: api-token
---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: external-dns-unifi-webhook-env
  namespace: doppler-operator-system
spec:
  # Audience format:
  # dopplerSecret:doppler-operator-system:external-dns-unifi-webhook-env
  identity: "REPLACE_WITH_DOPPLER_IDENTITY_ID"
  project: "REPLACE_WITH_DOPPLER_PROJECT"
  config: "REPLACE_WITH_DOPPLER_CONFIG"
  managedSecret:
    name: external-dns-unifi-webhook-env
    namespace: external-dns
    type: Opaque
  secrets:
    - UNIFI_HOST
    - UNIFI_API_KEY
    - UNIFI_SITE
    - UNIFI_SKIP_TLS_VERIFY
