apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workflows-argo
  namespace: argocd
spec:
  project: workloads
  source:
    repoURL: https://github.com/BordetNicolas/WorkflowsArgo.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: workflows-argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
