apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: doppler-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: platform
  source:
    repoURL: __ARGOCD_GIT_REPO__
    targetRevision: __ARGOCD_GIT_REVISION__
    path: gitops/doppler
    directory:
      recurse: false
      exclude: "doppler-service-token-secret.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: doppler-operator-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
