apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: platform
  source:
    repoURL: __ARGOCD_GIT_REPO__
    targetRevision: __ARGOCD_GIT_REVISION__
    path: gitops/external-dns
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
