apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workloads-project
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "9"
spec:
  project: platform
  source:
    repoURL: __ARGOCD_GIT_REPO__
    targetRevision: __ARGOCD_GIT_REVISION__
    path: gitops/projects
    directory:
      include: workloads.yaml
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
