apiVersion: v1
kind: Secret
metadata:
  name: external-dns-unifi-webhook-env
  namespace: external-dns
type: Opaque
stringData:
  UNIFI_HOST: __UNIFI_HOST__
  UNIFI_API_KEY: __UNIFI_API_KEY__
  UNIFI_SITE: __UNIFI_SITE__
  UNIFI_SKIP_TLS_VERIFY: "__UNIFI_SKIP_TLS_VERIFY__"
