apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Core platform components managed by GitOps (CNI, LB, ingress, storage, ArgoCD itself).
  sourceRepos:
    - "https://github.com/BordetNicolas/TalosGitOps.git"
    - "https://helm.cilium.io"
    - "https://argoproj.github.io/argo-helm"
    - "https://charts.jetstack.io"
    - "https://helm.doppler.com"
    - "https://metallb.github.io/metallb"
    - "https://kubernetes.github.io/ingress-nginx"
    - "https://charts.longhorn.io"
    - "https://kubernetes-sigs.github.io/external-dns/"
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: true
